import { WorkRequestsQuery } from 'types/graphql'

import { render } from '@redwoodjs/testing/web'

import OverviewCards from './OverviewCards'

//   Improve this test with help from the Redwood Testing Doc:
//    https://redwoodjs.com/docs/testing#testing-components

describe('OverviewCards', () => {
  it('renders successfully', () => {
    expect(() => {
      mockCurrentUser({ roles: ['ADMIN'] })
      render(<OverviewCards workRequests={workRequests} />)
    }).not.toThrow()
  })
})

const workRequests: WorkRequestsQuery['workRequests'] = [
  {
    __typename: 'WorkRequest',
    id: 'cm1vpqyhs0002xudmry6zcrpo',
    projectName: 'test',
    startDate: '2024-09-28T23:00:00.000Z',
    endDate: '2024-09-29T02:00:00.000Z',
    status: 'SUBMITTED',
    numWorkers: 1,
    location: {
      __typename: 'Address',
      id: 'cm113h9mw000z792d7vlbr92d',
      street: 'street',
      houseNumber: '24',
      city: 'Den Bosch',
      province: '',
      country: 'Netherlands',
      postalCode: '5433AA',
    },
    jobProfile: {
      __typename: 'JobProfile',
      id: 'cm1vnvasg0001e3g7mk9i3hju',
      name: 'Bedrijfsanalist',
      hourlyWageMin: 30,
      hourlyWageMax: 50,
    },
    shifts: [
      {
        __typename: 'Shift',
        id: 'cm1vpqyhs0003xudm0tpcyohm',
        status: 'UNFULFILLED',
        tempAgency: null,
      },
    ],
  },
  {
    __typename: 'WorkRequest',
    id: 'mock_work_request_4',
    projectName: 'Verzoek voor schoonmaak- en onderhoudsdiensten',
    startDate: '2024-10-01T14:00:00.000Z',
    endDate: '2024-10-01T17:30:00.000Z',
    status: 'CONFIRMED',
    numWorkers: 3,
    location: {
      __typename: 'Address',
      id: 'ckshg1h1p00021u6eyyhwvgsr',
      street: 'Coolsingel',
      houseNumber: '5',
      city: 'Rotterdam',
      province: 'Zuid-Holland',
      country: 'Netherlands',
      postalCode: '3012AA',
    },
    jobProfile: {
      __typename: 'JobProfile',
      id: 'ckldxzr7e000201jytllvxa45',
      name: 'Klantenservicemedewerker',
      hourlyWageMin: 18,
      hourlyWageMax: 28,
    },
    shifts: [
      {
        __typename: 'Shift',
        id: 'mock_shift_4_1',
        status: 'FULFILLED',
        tempAgency: {
          __typename: 'TempAgency',
          id: 'agency_2',
          name: 'SnelAanHetWerk',
          email: 'info@snelaanhetwerk.nl',
          phone: '+31 12 345 6789',
          address: {
            __typename: 'Address',
            street: 'Oude Gracht',
            houseNumber: '42',
            houseNumberAddition: 'B',
            postalCode: '3511AB',
            city: 'Utrecht',
          },
        },
      },
      {
        __typename: 'Shift',
        id: 'mock_shift_4_3',
        status: 'FULFILLED',
        tempAgency: {
          __typename: 'TempAgency',
          id: 'agency_1',
          name: 'FlexiWerk Oplossingen Drie',
          email: 'contact@flexiwerk.nl',
          phone: '+31 20 123 4949',
          address: {
            __typename: 'Address',
            street: 'Kalverstraat',
            houseNumber: '125',
            houseNumberAddition: '',
            postalCode: '1012PA',
            city: 'Amsterdam',
          },
        },
      },
      {
        __typename: 'Shift',
        id: 'mock_shift_4_2',
        status: 'FULFILLED',
        tempAgency: {
          __typename: 'TempAgency',
          id: 'agency_1',
          name: 'FlexiWerk Oplossingen Drie',
          email: 'contact@flexiwerk.nl',
          phone: '+31 20 123 4949',
          address: {
            __typename: 'Address',
            street: 'Kalverstraat',
            houseNumber: '125',
            houseNumberAddition: '',
            postalCode: '1012PA',
            city: 'Amsterdam',
          },
        },
      },
    ],
  },
  {
    __typename: 'WorkRequest',
    id: 'cm0znfez40001xtm4evkveu2s',
    projectName: '10 shifts ',
    startDate: '2024-09-08T11:00:00.000Z',
    endDate: '2024-09-08T15:00:00.000Z',
    status: 'CONFIRMED',
    numWorkers: 5,
    location: {
      __typename: 'Address',
      id: 'ckshg1h1p00021u6eyyhwvgsr',
      street: 'Coolsingel',
      houseNumber: '5',
      city: 'Rotterdam',
      province: 'Zuid-Holland',
      country: 'Netherlands',
      postalCode: '3012AA',
    },
    jobProfile: {
      __typename: 'JobProfile',
      id: 'ckldxzr7e000001jy5e5r3n1v',
      name: 'Salesmanager',
      hourlyWageMin: 30,
      hourlyWageMax: 55,
    },
    shifts: [
      {
        __typename: 'Shift',
        id: 'cm0znfez4000bxtm4ga3z7k3g',
        status: 'FULFILLED',
        tempAgency: {
          __typename: 'TempAgency',
          id: 'agency_2',
          name: 'SnelAanHetWerk',
          email: 'info@snelaanhetwerk.nl',
          phone: '+31 12 345 6789',
          address: {
            __typename: 'Address',
            street: 'Oude Gracht',
            houseNumber: '42',
            houseNumberAddition: 'B',
            postalCode: '3511AB',
            city: 'Utrecht',
          },
        },
      },
      {
        __typename: 'Shift',
        id: 'cm0znfez40002xtm4p54sqvqk',
        status: 'FULFILLED',
        tempAgency: {
          __typename: 'TempAgency',
          id: 'agency_2',
          name: 'SnelAanHetWerk',
          email: 'info@snelaanhetwerk.nl',
          phone: '+31 12 345 6789',
          address: {
            __typename: 'Address',
            street: 'Oude Gracht',
            houseNumber: '42',
            houseNumberAddition: 'B',
            postalCode: '3511AB',
            city: 'Utrecht',
          },
        },
      },
      {
        __typename: 'Shift',
        id: 'cm0znfez40003xtm4scdjuse1',
        status: 'FULFILLED',
        tempAgency: {
          __typename: 'TempAgency',
          id: 'agency_1',
          name: 'FlexiWerk Oplossingen Drie',
          email: 'contact@flexiwerk.nl',
          phone: '+31 20 123 4949',
          address: {
            __typename: 'Address',
            street: 'Kalverstraat',
            houseNumber: '125',
            houseNumberAddition: '',
            postalCode: '1012PA',
            city: 'Amsterdam',
          },
        },
      },
      {
        __typename: 'Shift',
        id: 'cm0znfez40004xtm453rt62ju',
        status: 'FULFILLED',
        tempAgency: {
          __typename: 'TempAgency',
          id: 'agency_1',
          name: 'FlexiWerk Oplossingen Drie',
          email: 'contact@flexiwerk.nl',
          phone: '+31 20 123 4949',
          address: {
            __typename: 'Address',
            street: 'Kalverstraat',
            houseNumber: '125',
            houseNumberAddition: '',
            postalCode: '1012PA',
            city: 'Amsterdam',
          },
        },
      },
      {
        __typename: 'Shift',
        id: 'cm0znfez40005xtm4uc11wle6',
        status: 'FULFILLED',
        tempAgency: {
          __typename: 'TempAgency',
          id: 'agency_1',
          name: 'FlexiWerk Oplossingen Drie',
          email: 'contact@flexiwerk.nl',
          phone: '+31 20 123 4949',
          address: {
            __typename: 'Address',
            street: 'Kalverstraat',
            houseNumber: '125',
            houseNumberAddition: '',
            postalCode: '1012PA',
            city: 'Amsterdam',
          },
        },
      },
    ],
  },
  {
    __typename: 'WorkRequest',
    id: 'cm0zo0pkk0004796aum9vq2ba',
    projectName: 'loading state shows all buttons',
    startDate: '2024-09-08T18:00:00.000Z',
    endDate: '2024-09-08T19:30:00.000Z',
    status: 'DRAFT',
    numWorkers: 5,
    location: {
      __typename: 'Address',
      id: 'ckshg1h1p00011u6e5t1tvnmv',
      street: 'Oude Gracht',
      houseNumber: '42',
      city: 'Utrecht',
      province: 'Utrecht',
      country: 'Netherlands',
      postalCode: '3511AB',
    },
    jobProfile: {
      __typename: 'JobProfile',
      id: 'ckldxzr7e000001jy5e5r3n1v',
      name: 'Salesmanager',
      hourlyWageMin: 30,
      hourlyWageMax: 55,
    },
    shifts: [
      {
        __typename: 'Shift',
        id: 'cm10k7st7000313btdtqjt4r0',
        status: 'UNFULFILLED',
        tempAgency: null,
      },
      {
        __typename: 'Shift',
        id: 'cm0zo0pkk0005796aiz1vuhz4',
        status: 'FULFILLED',
        tempAgency: {
          __typename: 'TempAgency',
          id: 'agency_1',
          name: 'FlexiWerk Oplossingen Drie',
          email: 'contact@flexiwerk.nl',
          phone: '+31 20 123 4949',
          address: {
            __typename: 'Address',
            street: 'Kalverstraat',
            houseNumber: '125',
            houseNumberAddition: '',
            postalCode: '1012PA',
            city: 'Amsterdam',
          },
        },
      },
      {
        __typename: 'Shift',
        id: 'cm0zo0pkk0006796a7odxebg0',
        status: 'FULFILLED',
        tempAgency: {
          __typename: 'TempAgency',
          id: 'agency_1',
          name: 'FlexiWerk Oplossingen Drie',
          email: 'contact@flexiwerk.nl',
          phone: '+31 20 123 4949',
          address: {
            __typename: 'Address',
            street: 'Kalverstraat',
            houseNumber: '125',
            houseNumberAddition: '',
            postalCode: '1012PA',
            city: 'Amsterdam',
          },
        },
      },
      {
        __typename: 'Shift',
        id: 'cm0zo0pkk0007796akdjarlvl',
        status: 'FULFILLED',
        tempAgency: {
          __typename: 'TempAgency',
          id: 'agency_1',
          name: 'FlexiWerk Oplossingen Drie',
          email: 'contact@flexiwerk.nl',
          phone: '+31 20 123 4949',
          address: {
            __typename: 'Address',
            street: 'Kalverstraat',
            houseNumber: '125',
            houseNumberAddition: '',
            postalCode: '1012PA',
            city: 'Amsterdam',
          },
        },
      },
      {
        __typename: 'Shift',
        id: 'cm0zo0pkk0009796abbw7g46y',
        status: 'FULFILLED',
        tempAgency: {
          __typename: 'TempAgency',
          id: 'agency_1',
          name: 'FlexiWerk Oplossingen Drie',
          email: 'contact@flexiwerk.nl',
          phone: '+31 20 123 4949',
          address: {
            __typename: 'Address',
            street: 'Kalverstraat',
            houseNumber: '125',
            houseNumberAddition: '',
            postalCode: '1012PA',
            city: 'Amsterdam',
          },
        },
      },
    ],
  },
  {
    __typename: 'WorkRequest',
    id: 'cm0y77a5r000o7hfcaxmtpovw',
    projectName: 'Test10',
    startDate: '2024-09-09T09:00:00.000Z',
    endDate: '2024-09-09T12:00:00.000Z',
    status: 'DONE',
    numWorkers: 2,
    location: {
      __typename: 'Address',
      id: 'ckshg1h1p00031u6e57zxzqyt',
      street: 'Hofstraat',
      houseNumber: '67',
      city: 'Arnhem',
      province: 'Gelderland',
      country: 'Netherlands',
      postalCode: '6811MA',
    },
    jobProfile: {
      __typename: 'JobProfile',
      id: 'ckldxzr7e000101jycp9l76vv',
      name: 'HR Specialist',
      hourlyWageMin: 28,
      hourlyWageMax: 42,
    },
    shifts: [
      {
        __typename: 'Shift',
        id: 'cm0y77a5r000p7hfcjcc9yvlo',
        status: 'FULFILLED',
        tempAgency: {
          __typename: 'TempAgency',
          id: 'agency_2',
          name: 'SnelAanHetWerk',
          email: 'info@snelaanhetwerk.nl',
          phone: '+31 12 345 6789',
          address: {
            __typename: 'Address',
            street: 'Oude Gracht',
            houseNumber: '42',
            houseNumberAddition: 'B',
            postalCode: '3511AB',
            city: 'Utrecht',
          },
        },
      },
      {
        __typename: 'Shift',
        id: 'cm10lzz3u0000cdtfwcne6lcz',
        status: 'UNFULFILLED',
        tempAgency: null,
      },
    ],
  },
  {
    __typename: 'WorkRequest',
    id: 'cm0zr9af90001bx584fli1tzv',
    projectName: 'EditedRefetch',
    startDate: '2024-09-14T08:00:00.000Z',
    endDate: '2024-09-14T12:00:00.000Z',
    status: 'SUBMITTED',
    numWorkers: 4,
    location: {
      __typename: 'Address',
      id: 'ckshg1h1p00011u6e5t1tvnmv',
      street: 'Oude Gracht',
      houseNumber: '42',
      city: 'Utrecht',
      province: 'Utrecht',
      country: 'Netherlands',
      postalCode: '3511AB',
    },
    jobProfile: {
      __typename: 'JobProfile',
      id: 'ckldxzr7e000001jy5e5r3n1v',
      name: 'Salesmanager',
      hourlyWageMin: 30,
      hourlyWageMax: 55,
    },
    shifts: [
      {
        __typename: 'Shift',
        id: 'cm0zr9af90002bx58j4t2s48z',
        status: 'UNFULFILLED',
        tempAgency: null,
      },
      {
        __typename: 'Shift',
        id: 'cm10iij9e000013btpsc0e6kc',
        status: 'UNFULFILLED',
        tempAgency: null,
      },
      {
        __typename: 'Shift',
        id: 'cm10jroqs000113btcw9vkv0j',
        status: 'UNFULFILLED',
        tempAgency: null,
      },
      {
        __typename: 'Shift',
        id: 'cm10jroqs000213btw2e9ujqk',
        status: 'UNFULFILLED',
        tempAgency: null,
      },
    ],
  },
]
