// Define your own mock data here:
export const standard = (/* vars, { ctx, req } */) => ({
  workRequests: [
    {
      __typename: 'WorkRequest',
      id: 'mock_work_request_5',
      projectName: 'Verzoek tot vervanging van verlichting',
      startDate: '2024-10-05T14:00:00.000Z',
      endDate: '2024-10-05T17:30:00.000Z',
      status: 'DONE',
      numWorkers: 3,
      location: {
        __typename: 'Address',
        id: 'ckshg1h1p00011u6e5t1tvnmv',
        street: 'Oude Gracht',
        houseNumber: '42',
        city: 'Utrecht',
        province: 'Utrecht',
        country: 'Netherlands',
        postalCode: '3511AB',
      },
      jobProfile: {
        __typename: 'JobProfile',
        id: 'ckldxzr7e000001jy5e5r3n1v',
        name: 'Salesmanager',
        hourlyWageMin: 30,
        hourlyWageMax: 55,
      },
      shifts: [
        {
          __typename: 'Shift',
          id: 'mock_shift_5_2',
          status: 'FULFILLED',
          tempAgency: {
            __typename: 'TempAgency',
            id: 'agency_2',
            name: 'SnelAanHetWerk',
            email: 'info@snelaanhetwerk.nl',
            phone: '+31 12 345 6789',
            address: {
              __typename: 'Address',
              street: 'Oude Gracht',
              houseNumber: '42',
              houseNumberAddition: 'B',
              postalCode: '3511AB',
              city: 'Utrecht',
            },
          },
        },
        {
          __typename: 'Shift',
          id: 'mock_shift_5_1',
          status: 'FULFILLED',
          tempAgency: {
            __typename: 'TempAgency',
            id: 'agency_2',
            name: 'SnelAanHetWerk',
            email: 'info@snelaanhetwerk.nl',
            phone: '+31 12 345 6789',
            address: {
              __typename: 'Address',
              street: 'Oude Gracht',
              houseNumber: '42',
              houseNumberAddition: 'B',
              postalCode: '3511AB',
              city: 'Utrecht',
            },
          },
        },
        {
          __typename: 'Shift',
          id: 'mock_shift_5_3',
          status: 'FULFILLED',
          tempAgency: {
            __typename: 'TempAgency',
            id: 'agency_3',
            name: 'TempoWerkers',
            email: 'info@tempowerkers.nl',
            phone: '+31 10 321 7654',
            address: {
              __typename: 'Address',
              street: 'Hofstraat',
              houseNumber: '67',
              houseNumberAddition: 'C',
              postalCode: '6811MA',
              city: 'Arnhem',
            },
          },
        },
      ],
    },
    {
      __typename: 'WorkRequest',
      id: 'mock_work_request_4',
      projectName: 'Verzoek voor schoonmaak- en onderhoudsdiensten',
      startDate: '2024-10-01T14:00:00.000Z',
      endDate: '2024-10-01T17:30:00.000Z',
      status: 'CONFIRMED',
      numWorkers: 3,
      location: {
        __typename: 'Address',
        id: 'ckshg1h1p00021u6eyyhwvgsr',
        street: 'Coolsingel',
        houseNumber: '5',
        city: 'Rotterdam',
        province: 'Zuid-Holland',
        country: 'Netherlands',
        postalCode: '3012AA',
      },
      jobProfile: {
        __typename: 'JobProfile',
        id: 'ckldxzr7e000201jytllvxa45',
        name: 'Klantenservicemedewerker',
        hourlyWageMin: 18,
        hourlyWageMax: 28,
      },
      shifts: [
        {
          __typename: 'Shift',
          id: 'mock_shift_4_1',
          status: 'FULFILLED',
          tempAgency: {
            __typename: 'TempAgency',
            id: 'agency_2',
            name: 'SnelAanHetWerk',
            email: 'info@snelaanhetwerk.nl',
            phone: '+31 12 345 6789',
            address: {
              __typename: 'Address',
              street: 'Oude Gracht',
              houseNumber: '42',
              houseNumberAddition: 'B',
              postalCode: '3511AB',
              city: 'Utrecht',
            },
          },
        },
        {
          __typename: 'Shift',
          id: 'mock_shift_4_3',
          status: 'FULFILLED',
          tempAgency: {
            __typename: 'TempAgency',
            id: 'agency_1',
            name: 'FlexiWerk Oplossingen Drie',
            email: 'contact@flexiwerk.nl',
            phone: '+31 20 123 4949',
            address: {
              __typename: 'Address',
              street: 'Kalverstraat',
              houseNumber: '125',
              houseNumberAddition: '',
              postalCode: '1012PA',
              city: 'Amsterdam',
            },
          },
        },
        {
          __typename: 'Shift',
          id: 'mock_shift_4_2',
          status: 'FULFILLED',
          tempAgency: {
            __typename: 'TempAgency',
            id: 'agency_1',
            name: 'FlexiWerk Oplossingen Drie',
            email: 'contact@flexiwerk.nl',
            phone: '+31 20 123 4949',
            address: {
              __typename: 'Address',
              street: 'Kalverstraat',
              houseNumber: '125',
              houseNumberAddition: '',
              postalCode: '1012PA',
              city: 'Amsterdam',
            },
          },
        },
      ],
    },
    {
      __typename: 'WorkRequest',
      id: 'cm0zpqytp0001120bahb2698a',
      projectName: 'Nami',
      startDate: '2024-09-15T08:00:00.000Z',
      endDate: '2024-09-22T11:00:00.000Z',
      status: 'SUBMITTED',
      numWorkers: 1,
      location: {
        __typename: 'Address',
        id: 'cm112p59h0003tro0778nqhmi',
        street: 'asdf',
        houseNumber: 'asdf',
        city: 'asdf',
        province: '',
        country: 'Netherlands',
        postalCode: '1234BB',
      },
      jobProfile: {
        __typename: 'JobProfile',
        id: 'ckldxzr7e000001jy5e5r3n1v',
        name: 'Salesmanager',
        hourlyWageMin: 30,
        hourlyWageMax: 55,
      },
      shifts: [
        {
          __typename: 'Shift',
          id: 'cm0zpqytp0002120bivxxdoh2',
          status: 'UNFULFILLED',
          tempAgency: null,
        },
      ],
    },
  ],
})
